// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#if __has_include("arduino_secrets.h")
#include "arduino_secrets.h"
#else // In tests, use the following constants instead of reading from arduino_secrets.h as it is not present
#define SECRET_DEVICE_KEY "1FHKGMPOXVBHTYUAZU2J" // This pretty much random, please don't try to use it
#define SECRET_SSID "SSID"
#define SECRET_OPTIONAL_PASS "PASSWORD"
#endif
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "498545b4-053d-49d1-9d7f-548d689357b9";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLedCountsChange();
void onInnerStripColorChange();
void onOuterStripColorChange();
void onSmallStripColorChange();
void onTriggerSwitchChange();

String ledCounts;
CloudColor innerStripColor;
CloudColor outerStripColor;
CloudColor smallStripColor;
bool triggerSwitch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);  
  ArduinoCloud.addProperty(innerStripColor, READWRITE, ON_CHANGE, onInnerStripColorChange);
  ArduinoCloud.addProperty(outerStripColor, READWRITE, ON_CHANGE, onOuterStripColorChange);
  ArduinoCloud.addProperty(smallStripColor, READWRITE, ON_CHANGE, onSmallStripColorChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
